baseURL = 'https://garlic-signage.com/'
languageCode = 'en-us'
title = 'GarlicSignage - Open Source Software for Digital Signage '
theme = 'garlic-signage'
buildDrafts = true
buildFuture = true
buildExpired = true

enableGitInfo = true

[module]
  [[module.imports]]

[frontmatter]
  date = [':fileModTime', ':default']
  lastmod = [':fileModTime']

[security]
  enableInlineShortcodes = true

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = false