baseURL = 'https://garlic-signage.com/'
languageCode = 'en-us'
title = 'GarlicSignage - Open Source Software for Digital Signage '
theme = 'garlic-signage'
buildDrafts = true
buildFuture = true
buildExpired = true

enableGitInfo = true

[frontmatter]
  date = [':fileModTime', ':default']
  lastmod = [':fileModTime']

[security]
  enableInlineShortcodes = true