baseURL = 'https://example.org/'
languageCode = 'en-US'

[menus]
  [[menus.main]]
    name = 'GarlicSignage'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Player'
    pageRef = '/garlic-player'
    weight = 20

  [[menus.main]]
    name = 'Management'
    pageRef = '/garlic-hub'
    weight = 30

  [[menus.main]]
    name = 'Launcher'
    pageRef = '/garlic-launcher'
    weight = 40

  [[menus.main]]
    name = 'Proxy'
    pageRef = '/garlic-proxy'
    weight = 50

  [[menus.main]]
    name = 'Resources'
    pageRef = '/resources'
    weight = 60
